   version: '3'
   services:
     app:
       image: mcr.microsoft.com/devcontainers/python:3
       volumes:
         - ..:/workspace:cached
       command: sleep infinity
       network_mode: service:db
       
     db:
       image: mysql:8.0
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: librarydb
         MYSQL_DATABASE: librarydb
         MYSQL_USER: library_user
         MYSQL_PASSWORD: library_password
       volumes:
         - mysql-data:/var/lib/mysql
       ports:
         - "3306:3306"

   volumes:
     mysql-data: